### ISSUE TITLE
curses: window is already NULL but still used

### ISSUE THREAD

**Issue by Rhialto** [NetHack/NetHack#1090]
Hi! I am currently in the process of adapting the pkgsrc packaging of NetHack 3.6.7 to include the curses window option. A bit late perhaps...

While working on that, I ran into a case of a NULL pointer being used. Apparently when linking with ncurses, this doesn't cause problems, but NetBSD's own curses doesn't like it, and crashes the game.

Here is the stack trace. It happens when `#quit`ting, I think just before the high scores are about to be shown (but I guess it should show in the stack trace if I'm totally correct with that):
```
(gdb) bt
#0  redrawwin (win=0x0) at /usr/src/lib/libcurses/touchwin.c:149
#1  0x0000000017e104b4 in curses_refresh_nethack_windows () at ../win/curses/curswins.c:176
#2  0x0000000017e1054a in curses_destroy_win (win=win@entry=0x7ad219520540) at ../win/curses/curswins.c:155
#3  0x0000000017e1512c in curses_display_nhmenu (wid=<optimized out>, how=<optimized out>, _selected=0x7f7fff65d850) at ../win/curses/cursdial.c:771
#4  0x0000000017e0ff81 in curses_select_menu (wid=wid@entry=21, how=how@entry=0, selected=selected@entry=0x7f7fff65d850) at ../win/curses/cursmain.c:607
#5  0x0000000017e10257 in curses_display_nhwindow (wid=21, block=1) at ../win/curses/cursmain.c:385
#6  0x0000000017ca8075 in really_done (how=<optimized out>, how@entry=13) at end.c:1609
#7  0x0000000017ca993f in done (how=how@entry=13) at end.c:1201
#8  0x0000000017ca9c85 in done2 () at end.c:381
#9  done2 () at end.c:337
#10 0x0000000017c489da in doextcmd () at cmd.c:363
#11 0x0000000017c57e94 in rhack (cmd=<optimized out>, cmd@entry=0x0) at cmd.c:4909
#12 0x0000000017c265da in moveloop (resuming=<optimized out>) at allmain.c:435
#13 0x0000000017e1b862 in main (argc=<optimized out>, argv=<optimized out>) at ../sys/unix/unixmain.c:351
```
`status_window` is NULL here. Simply checking for NULL avoids the problem. I added checks for the other windows as well, while I was there.
```
--- win/curses/curswins.c.orig  2023-08-28 19:22:25.737331832 +0000
+++ win/curses/curswins.c
@@ -173,12 +173,18 @@ curses_refresh_nethack_windows()
         touchwin(stdscr);
         refresh();
     } else {
-        touchwin(status_window);
-        wnoutrefresh(status_window);
-        touchwin(map_window);
-        wnoutrefresh(map_window);
-        touchwin(message_window);
-        wnoutrefresh(message_window);
+        if (status_window) {
+            touchwin(status_window);
+            wnoutrefresh(status_window);
+        }
+        if (map_window) {
+            touchwin(map_window);
+            wnoutrefresh(map_window);
+        }
+        if (message_window) {
+            touchwin(message_window);
+            wnoutrefresh(message_window);
+        }
         if (inv_window) {
             touchwin(inv_window);
             wnoutrefresh(inv_window);
```

**Comment by entrez** [comment]
It seems like this was already fixed in the 3.7 branch with 31862b95b033ceba382f1b7188b033c20f860563, just wasn't backported to 3.6.

**Comment by Rhialto** [comment]
Ah, that's great to hear. With the label it looks like you would backport it to 3.6, so I won't close it just yet, but thanks anyway!

**Comment by nhmall** [comment]
963c3ac In branch NetHack-3.6

**Comment by Rhialto** [comment]
Thanks! I'll close this issue then.
