### ISSUE TITLE
Impossible:  "floor sanity no_charge obj not inside tended shop! 50b000bec160 floor: 4 uncursed worthless pieces of blue glass"

### ISSUE THREAD

**Issue by mkuoppal** [NetHack/NetHack#1317]
#5  0x0000555556ca8e70 in NH_abort (
    why=0x7ffff4957c60 "floor sanity no_charge obj not inside tended shop! 50b000bec160 floor: 4 uncursed worthless pieces of blue glass")
    at end.c:1931
#6  0x0000555556c94900 in panic (str=0x555557a9f160 "%s") at end.c:461
#7  0x00005555571c5985 in impossible (s=0x5555579ad040 "%s no_charge obj not inside tended shop! %s %s: %s") at pline.c:585
#8  0x0000555556f33f01 in insane_object (obj=0x50b000bec160, fmt=0x5555579ad040 "%s no_charge obj not inside tended shop! %s %s: %s",
    mesg=0x5555579ac5c0 "floor sanity", mon=0x0) at mkobj.c:3235
#9  0x0000555556f32557 in shop_obj_sanity (obj=0x50b000bec160, mesg=0x5555579ac5c0 "floor sanity") at mkobj.c:3108
#10 0x0000555556f304b4 in objlist_sanity (objlist=0x50b000ce3cd0, wheretype=1, mesg=0x5555579ac5c0 "floor sanity") at mkobj.c:2966
#11 0x0000555556f2ee13 in obj_sanity_check () at mkobj.c:2866
#12 0x000055555763b086 in sanity_check () at wizcmds.c:1448
#13 0x0000555556920654 in moveloop_core () at allmain.c:183
#14 0x0000555556924df8 in moveloop (resuming=0 '\000') at allmain.c:562

**Comment by paxed** [comment]
This is practically impossible to figure out from the backtrace. I think I fixed at least one case of this in commit ba731a3
 and haven't seen another yet.

**Comment by paxed** [comment]
Finally fuzzer session managed to trigger this, and I figured it out from there. Fix is incoming.
